# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - test-rolleoppslag

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install dependencies and build
        run: |
          npm ci
          npm run build

      - name: Prepare deployment package
        run: |
          mkdir deploy
          cp -r server deploy/
          mkdir -p deploy/client
          cp -r client/dist deploy/client/
          cp package.json package-lock.json deploy/
          cd deploy
          npm ci --omit=dev --workspace server

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_A83AE7E52BB7494B8551766025B62A46 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_3248C84E8C524BEAA0694DF2923F2C64 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_18E0CD20BA7F4644A2DF5111035EF0BF }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'test-rolleoppslag'
          slot-name: 'Production'
          package: deploy
          startup-command: 'node server/src/index.js'
